theme: jekyll-theme-chirpy

lang: en
timezone: Europe/Copenhagen

title: Zsófia Tóth
tagline: Software Engineer
description: >-
  To be filled out.

url: "https://zsofitoth.github.io"

github:
  username: zsofitoth

social:
  name: Zsófia Tóth-Coconetu
  links:
    - https://github.com/zsofitoth

avatar: https://github.com/zsofitoth.png

paginate: 10

theme_mode: # light | dark

toc: true

comments:
  provider: # disqus | utterances | giscus

analytics:
  google:
    id:

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
